#!/usr/bin/env bash

input=$1
if [ -z `echo $1 | grep '.q$'` ]; then
  input=$input".q"
fi

LIST=""
for F in ql/src/test/queries/negative/$input
do
  if [[ -n $LIST ]] ; then
    LIST=${LIST},`basename $F`
  else
    LIST=`basename $F`
  fi
done

echo testing $LIST
ant test -Dtestcase=TestParseNegative -Dqfile=$LIST -Dmodule=ql -Dtest.silent=false -Doverwrite=true
