#!/usr/bin/env bash

if [[ -n $1 ]] ; then
  version=$1
else
  version="0.8.0-nr1000-SNAPSHOT"
fi

bin=`dirname "$0"`
libs=`cat $bin/hive-$version`
for lib in $libs
do
  if [ "$lib" == "exec" ]
  then loc="ql" 
  else loc=$lib
  fi
  mvn install:install-file -Dfile=./build/$loc/hive-$lib-$version.jar -DgroupId=org.apache.hive -DartifactId=hive-$lib -Dversion=$version -Dpackaging=jar -DgeneratePom=true
done
