#!/usr/bin/env bash

if [[ -z $1 ]] ; then
  $1="ql"
fi

MODULES=""
for module in $@
do
  if [[ -n $MODULES ]] ; then
    MODULES=${MODULES},$module
  else
    MODULES=$module
  fi
done

echo Building.. $MODULES

ant jar -Dmodule=$MODULES -Doffilne=true
for module in $@
do
  cp build/$module/hive-*.jar build/dist/lib/
  cp build/$module/hive-*.jar build/ivy/lib/default/
  cp build/$module/hive-*.jar build/ivy/lib/test/
done

