#!/usr/bin/env bash

input=$1
if [ -z `echo $1 | grep '.q$'` ]; then
  input=$input".q"
fi

LIST=""
for F in /home/navis/apache/oss-hive/ql/src/test/queries/clientnegative/$input
do
  if [[ -n $LIST ]] ; then
    LIST=${LIST},`basename $F`
  else
    LIST=`basename $F`
  fi
done

echo testing $LIST
mvn test -Dtest=TestNegativeCliDriver -Dqfile=$LIST -Phadoop-1 -Dtest.output.overwrite=true
